version: 2

jobs:
  test:
    working_directory: /tmp/project
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            echo "planning!!"
            "a sample text" > file-lists.txt
      - persist_to_workspace:
          root: .
          paths:
            - .

  workspace:
    steps:
      - attach_workspace:
          at: .
      - run:
          name: is file there
          command: |
            ls
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - test
      - workspace:
          requires:
            - test
