version: 2

jobs:
  test:
    working_directory: /tmp/project
    docker: 
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            echo "planning!!"
            echo "a sample text" > file-lists.txt
      - persist_to_workspace:
          root: .
          paths: 
            - /tmp/project

  workspace:
    docker: 
      - image: cimg/node:current
    steps:
      - run:
          name: is file there
          command: ls

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - test
      - workspace:
          requires:
            - test
